version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://192.168.2.244:3000
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MQTT_BROKER_URL=mqtt://192.168.2.33:1883
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log: 